In [1]:
import numpy as np, pandas as pd

In [2]:
df = pd.read_csv('forked_Bigdata_Analyst_Cert/part4/ch7/air_quality.csv')

## Data type transform

In [5]:
df.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Temp         int64
Month        int64
Day          int64
dtype: object

In [11]:
dfk = df.copy()
dfk['months'] = dfk['Month'].astype('int')
dfk

     Ozone  Solar.R  Wind  Temp  Month  Day month  months
0     41.0    190.0   7.4    67      5    1     5       5
1     36.0    118.0   8.0    72      5    2     5       5
2     12.0    149.0  12.6    74      5    3     5       5
3     18.0    313.0  11.5    62      5    4     5       5
4      NaN      NaN  14.3    56      5    5     5       5
..     ...      ...   ...   ...    ...  ...   ...     ...
148   30.0    193.0   6.9    70      9   26     9       9
149    NaN    145.0  13.2    77      9   27     9       9
150   14.0    191.0  14.3    75      9   28     9       9
151   18.0    131.0   8.0    76      9   29     9       9
152   20.0    223.0  11.5    68      9   30     9       9

[153 rows x 8 columns]

### check duplicated rows

In [17]:
df.duplicated().sum()
df.drop_duplicates()

     Ozone  Solar.R  Wind  Temp  Month  Day month  months
0     41.0    190.0   7.4    67      5    1     5       5
1     36.0    118.0   8.0    72      5    2     5       5
2     12.0    149.0  12.6    74      5    3     5       5
3     18.0    313.0  11.5    62      5    4     5       5
4      NaN      NaN  14.3    56      5    5     5       5
..     ...      ...   ...   ...    ...  ...   ...     ...
148   30.0    193.0   6.9    70      9   26     9       9
149    NaN    145.0  13.2    77      9   27     9       9
150   14.0    191.0  14.3    75      9   28     9       9
151   18.0    131.0   8.0    76      9   29     9       9
152   20.0    223.0  11.5    68      9   30     9       9

[153 rows x 8 columns]

## Process Datetime Data

In [13]:
import datetime #cannot use in exam

In [14]:
help(pd.Series.dt)

Help on class CombinedDatetimelikeProperties in module pandas.core.indexes.accessors:

class CombinedDatetimelikeProperties(DatetimeProperties, TimedeltaProperties, PeriodProperties)
 |  CombinedDatetimelikeProperties(data: 'Series')
 |
 |  Method resolution order:
 |      CombinedDatetimelikeProperties
 |      DatetimeProperties
 |      TimedeltaProperties
 |      PeriodProperties
 |      Properties
 |      pandas.core.accessor.PandasDelegate
 |      pandas.core.base.PandasObject
 |      pandas.core.accessor.DirNamesMixin
 |      pandas.core.base.NoNewAttributesMixin
 |      builtins.object
 |
 |  Static methods defined here:
 |
 |  __new__(cls, data: 'Series')
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __annotations__ = {}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from DatetimeProperties:
 |
 |  as_unit(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |
 |  ceil(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |      Perform ceil operation on the data to the specified `freq`.
 |
 |      Parameters
 |      ----------
 |      freq : str or Offset
 |          The frequency level to ceil the index to. Must be a fixed
 |          frequency like 'S' (second) not 'ME' (month end). See
 |          :ref:`frequency aliases <timeseries.offset_aliases>` for
 |          a list of possible `freq` values.
 |      ambiguous : 'infer', bool-ndarray, 'NaT', default 'raise'
 |          Only relevant for DatetimeIndex:
 |
 |          - 'infer' will attempt to infer fall dst-transition hours based on
 |            order
 |          - bool-ndarray where True signifies a DST time, False designates
 |            a non-DST time (note that this flag is only applicable for
 |            ambiguous times)
 |          - 'NaT' will return NaT where there are ambiguous times
 |          - 'raise' will raise an AmbiguousTimeError if there are ambiguous
 |            times.
 |
 |      nonexistent : 'shift_forward', 'shift_backward', 'NaT', timedelta, default 'raise'
 |          A nonexistent time does not exist in a particular timezone
 |          where clocks moved forward due to DST.
 |
 |          - 'shift_forward' will shift the nonexistent time forward to the
 |            closest existing time
 |          - 'shift_backward' will shift the nonexistent time backward to the
 |            closest existing time
 |          - 'NaT' will return NaT where there are nonexistent times
 |          - timedelta objects will shift nonexistent times by the timedelta
 |          - 'raise' will raise an NonExistentTimeError if there are
 |            nonexistent times.
 |
 |      Returns
 |      -------
 |      DatetimeIndex, TimedeltaIndex, or Series
 |          Index of the same type for a DatetimeIndex or TimedeltaIndex,
 |          or a Series with the same index for a Series.
 |
 |      Raises
 |      ------
 |      ValueError if the `freq` cannot be converted.
 |
 |      Notes
 |      -----
 |      If the timestamps have a timezone, ceiling will take place relative to the
 |      local ("wall") time and re-localized to the same timezone. When ceiling
 |      near daylight savings time, use ``nonexistent`` and ``ambiguous`` to
 |      control the re-localization behavior.
 |
 |      Examples
 |      --------
 |      **DatetimeIndex**
 |
 |      >>> rng = pd.date_range('1/1/2018 11:59:00', periods=3, freq='min')
 |      >>> rng
 |      DatetimeIndex(['2018-01-01 11:59:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 12:01:00'],
 |                    dtype='datetime64[ns]', freq='min')
 |      >>> rng.ceil('h')
 |      DatetimeIndex(['2018-01-01 12:00:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 13:00:00'],
 |                    dtype='datetime64[ns]', freq=None)
 |
 |      **Series**
 |
 |      >>> pd.Series(rng).dt.ceil("h")
 |      0   2018-01-01 12:00:00
 |      1   2018-01-01 12:00:00
 |      2   2018-01-01 13:00:00
 |      dtype: datetime64[ns]
 |
 |      When rounding near a daylight savings time transition, use ``ambiguous`` or
 |      ``nonexistent`` to control how the timestamp should be re-localized.
 |
 |      >>> rng_tz = pd.DatetimeIndex(["2021-10-31 01:30:00"], tz="Europe/Amsterdam")
 |
 |      >>> rng_tz.ceil("h", ambiguous=False)
 |      DatetimeIndex(['2021-10-31 02:00:00+01:00'],
 |                    dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
 |
 |      >>> rng_tz.ceil("h", ambiguous=True)
 |      DatetimeIndex(['2021-10-31 02:00:00+02:00'],
 |                    dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
 |
 |  day_name(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |      Return the day names with specified locale.
 |
 |      Parameters
 |      ----------
 |      locale : str, optional
 |          Locale determining the language in which to return the day name.
 |          Default is English locale (``'en_US.utf8'``). Use the command
 |          ``locale -a`` on your terminal on Unix systems to find your locale
 |          language code.
 |
 |      Returns
 |      -------
 |      Series or Index
 |          Series or Index of day names.
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series(pd.date_range(start='2018-01-01', freq='D', periods=3))
 |      >>> s
 |      0   2018-01-01
 |      1   2018-01-02
 |      2   2018-01-03
 |      dtype: datetime64[ns]
 |      >>> s.dt.day_name()
 |      0       Monday
 |      1      Tuesday
 |      2    Wednesday
 |      dtype: object
 |
 |      >>> idx = pd.date_range(start='2018-01-01', freq='D', periods=3)
 |      >>> idx
 |      DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03'],
 |                    dtype='datetime64[ns]', freq='D')
 |      >>> idx.day_name()
 |      Index(['Monday', 'Tuesday', 'Wednesday'], dtype='object')
 |
 |      Using the ``locale`` parameter you can set a different locale language,
 |      for example: ``idx.day_name(locale='pt_BR.utf8')`` will return day
 |      names in Brazilian Portuguese language.
 |
 |      >>> idx = pd.date_range(start='2018-01-01', freq='D', periods=3)
 |      >>> idx
 |      DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03'],
 |                    dtype='datetime64[ns]', freq='D')
 |      >>> idx.day_name(locale='pt_BR.utf8') # doctest: +SKIP
 |      Index(['Segunda', 'Terça', 'Quarta'], dtype='object')
 |
 |  floor(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |      Perform floor operation on the data to the specified `freq`.
 |
 |      Parameters
 |      ----------
 |      freq : str or Offset
 |          The frequency level to floor the index to. Must be a fixed
 |          frequency like 'S' (second) not 'ME' (month end). See
 |          :ref:`frequency aliases <timeseries.offset_aliases>` for
 |          a list of possible `freq` values.
 |      ambiguous : 'infer', bool-ndarray, 'NaT', default 'raise'
 |          Only relevant for DatetimeIndex:
 |
 |          - 'infer' will attempt to infer fall dst-transition hours based on
 |            order
 |          - bool-ndarray where True signifies a DST time, False designates
 |            a non-DST time (note that this flag is only applicable for
 |            ambiguous times)
 |          - 'NaT' will return NaT where there are ambiguous times
 |          - 'raise' will raise an AmbiguousTimeError if there are ambiguous
 |            times.
 |
 |      nonexistent : 'shift_forward', 'shift_backward', 'NaT', timedelta, default 'raise'
 |          A nonexistent time does not exist in a particular timezone
 |          where clocks moved forward due to DST.
 |
 |          - 'shift_forward' will shift the nonexistent time forward to the
 |            closest existing time
 |          - 'shift_backward' will shift the nonexistent time backward to the
 |            closest existing time
 |          - 'NaT' will return NaT where there are nonexistent times
 |          - timedelta objects will shift nonexistent times by the timedelta
 |          - 'raise' will raise an NonExistentTimeError if there are
 |            nonexistent times.
 |
 |      Returns
 |      -------
 |      DatetimeIndex, TimedeltaIndex, or Series
 |          Index of the same type for a DatetimeIndex or TimedeltaIndex,
 |          or a Series with the same index for a Series.
 |
 |      Raises
 |      ------
 |      ValueError if the `freq` cannot be converted.
 |
 |      Notes
 |      -----
 |      If the timestamps have a timezone, flooring will take place relative to the
 |      local ("wall") time and re-localized to the same timezone. When flooring
 |      near daylight savings time, use ``nonexistent`` and ``ambiguous`` to
 |      control the re-localization behavior.
 |
 |      Examples
 |      --------
 |      **DatetimeIndex**
 |
 |      >>> rng = pd.date_range('1/1/2018 11:59:00', periods=3, freq='min')
 |      >>> rng
 |      DatetimeIndex(['2018-01-01 11:59:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 12:01:00'],
 |                    dtype='datetime64[ns]', freq='min')
 |      >>> rng.floor('h')
 |      DatetimeIndex(['2018-01-01 11:00:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 12:00:00'],
 |                    dtype='datetime64[ns]', freq=None)
 |
 |      **Series**
 |
 |      >>> pd.Series(rng).dt.floor("h")
 |      0   2018-01-01 11:00:00
 |      1   2018-01-01 12:00:00
 |      2   2018-01-01 12:00:00
 |      dtype: datetime64[ns]
 |
 |      When rounding near a daylight savings time transition, use ``ambiguous`` or
 |      ``nonexistent`` to control how the timestamp should be re-localized.
 |
 |      >>> rng_tz = pd.DatetimeIndex(["2021-10-31 03:30:00"], tz="Europe/Amsterdam")
 |
 |      >>> rng_tz.floor("2h", ambiguous=False)
 |      DatetimeIndex(['2021-10-31 02:00:00+01:00'],
 |                   dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
 |
 |      >>> rng_tz.floor("2h", ambiguous=True)
 |      DatetimeIndex(['2021-10-31 02:00:00+02:00'],
 |                    dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
 |
 |  isocalendar(self) -> 'DataFrame'
 |      Calculate year, week, and day according to the ISO 8601 standard.
 |
 |      Returns
 |      -------
 |      DataFrame
 |          With columns year, week and day.
 |
 |      See Also
 |      --------
 |      Timestamp.isocalendar : Function return a 3-tuple containing ISO year,
 |          week number, and weekday for the given Timestamp object.
 |      datetime.date.isocalendar : Return a named tuple object with
 |          three components: year, week and weekday.
 |
 |      Examples
 |      --------
 |      >>> ser = pd.to_datetime(pd.Series(["2010-01-01", pd.NaT]))
 |      >>> ser.dt.isocalendar()
 |         year  week  day
 |      0  2009    53     5
 |      1  <NA>  <NA>  <NA>
 |      >>> ser.dt.isocalendar().week
 |      0      53
 |      1    <NA>
 |      Name: week, dtype: UInt32
 |
 |  month_name(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |      Return the month names with specified locale.
 |
 |      Parameters
 |      ----------
 |      locale : str, optional
 |          Locale determining the language in which to return the month name.
 |          Default is English locale (``'en_US.utf8'``). Use the command
 |          ``locale -a`` on your terminal on Unix systems to find your locale
 |          language code.
 |
 |      Returns
 |      -------
 |      Series or Index
 |          Series or Index of month names.
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series(pd.date_range(start='2018-01', freq='ME', periods=3))
 |      >>> s
 |      0   2018-01-31
 |      1   2018-02-28
 |      2   2018-03-31
 |      dtype: datetime64[ns]
 |      >>> s.dt.month_name()
 |      0     January
 |      1    February
 |      2       March
 |      dtype: object
 |
 |      >>> idx = pd.date_range(start='2018-01', freq='ME', periods=3)
 |      >>> idx
 |      DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31'],
 |                    dtype='datetime64[ns]', freq='ME')
 |      >>> idx.month_name()
 |      Index(['January', 'February', 'March'], dtype='object')
 |
 |      Using the ``locale`` parameter you can set a different locale language,
 |      for example: ``idx.month_name(locale='pt_BR.utf8')`` will return month
 |      names in Brazilian Portuguese language.
 |
 |      >>> idx = pd.date_range(start='2018-01', freq='ME', periods=3)
 |      >>> idx
 |      DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31'],
 |                    dtype='datetime64[ns]', freq='ME')
 |      >>> idx.month_name(locale='pt_BR.utf8')  # doctest: +SKIP
 |      Index(['Janeiro', 'Fevereiro', 'Março'], dtype='object')
 |
 |  normalize(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |      Convert times to midnight.
 |
 |      The time component of the date-time is converted to midnight i.e.
 |      00:00:00. This is useful in cases, when the time does not matter.
 |      Length is unaltered. The timezones are unaffected.
 |
 |      This method is available on Series with datetime values under
 |      the ``.dt`` accessor, and directly on Datetime Array/Index.
 |
 |      Returns
 |      -------
 |      DatetimeArray, DatetimeIndex or Series
 |          The same type as the original data. Series will have the same
 |          name and index. DatetimeIndex will have the same name.
 |
 |      See Also
 |      --------
 |      floor : Floor the datetimes to the specified freq.
 |      ceil : Ceil the datetimes to the specified freq.
 |      round : Round the datetimes to the specified freq.
 |
 |      Examples
 |      --------
 |      >>> idx = pd.date_range(start='2014-08-01 10:00', freq='h',
 |      ...                     periods=3, tz='Asia/Calcutta')
 |      >>> idx
 |      DatetimeIndex(['2014-08-01 10:00:00+05:30',
 |                     '2014-08-01 11:00:00+05:30',
 |                     '2014-08-01 12:00:00+05:30'],
 |                      dtype='datetime64[ns, Asia/Calcutta]', freq='h')
 |      >>> idx.normalize()
 |      DatetimeIndex(['2014-08-01 00:00:00+05:30',
 |                     '2014-08-01 00:00:00+05:30',
 |                     '2014-08-01 00:00:00+05:30'],
 |                     dtype='datetime64[ns, Asia/Calcutta]', freq=None)
 |
 |  round(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |      Perform round operation on the data to the specified `freq`.
 |
 |      Parameters
 |      ----------
 |      freq : str or Offset
 |          The frequency level to round the index to. Must be a fixed
 |          frequency like 'S' (second) not 'ME' (month end). See
 |          :ref:`frequency aliases <timeseries.offset_aliases>` for
 |          a list of possible `freq` values.
 |      ambiguous : 'infer', bool-ndarray, 'NaT', default 'raise'
 |          Only relevant for DatetimeIndex:
 |
 |          - 'infer' will attempt to infer fall dst-transition hours based on
 |            order
 |          - bool-ndarray where True signifies a DST time, False designates
 |            a non-DST time (note that this flag is only applicable for
 |            ambiguous times)
 |          - 'NaT' will return NaT where there are ambiguous times
 |          - 'raise' will raise an AmbiguousTimeError if there are ambiguous
 |            times.
 |
 |      nonexistent : 'shift_forward', 'shift_backward', 'NaT', timedelta, default 'raise'
 |          A nonexistent time does not exist in a particular timezone
 |          where clocks moved forward due to DST.
 |
 |          - 'shift_forward' will shift the nonexistent time forward to the
 |            closest existing time
 |          - 'shift_backward' will shift the nonexistent time backward to the
 |            closest existing time
 |          - 'NaT' will return NaT where there are nonexistent times
 |          - timedelta objects will shift nonexistent times by the timedelta
 |          - 'raise' will raise an NonExistentTimeError if there are
 |            nonexistent times.
 |
 |      Returns
 |      -------
 |      DatetimeIndex, TimedeltaIndex, or Series
 |          Index of the same type for a DatetimeIndex or TimedeltaIndex,
 |          or a Series with the same index for a Series.
 |
 |      Raises
 |      ------
 |      ValueError if the `freq` cannot be converted.
 |
 |      Notes
 |      -----
 |      If the timestamps have a timezone, rounding will take place relative to the
 |      local ("wall") time and re-localized to the same timezone. When rounding
 |      near daylight savings time, use ``nonexistent`` and ``ambiguous`` to
 |      control the re-localization behavior.
 |
 |      Examples
 |      --------
 |      **DatetimeIndex**
 |
 |      >>> rng = pd.date_range('1/1/2018 11:59:00', periods=3, freq='min')
 |      >>> rng
 |      DatetimeIndex(['2018-01-01 11:59:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 12:01:00'],
 |                    dtype='datetime64[ns]', freq='min')
 |      >>> rng.round('h')
 |      DatetimeIndex(['2018-01-01 12:00:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 12:00:00'],
 |                    dtype='datetime64[ns]', freq=None)
 |
 |      **Series**
 |
 |      >>> pd.Series(rng).dt.round("h")
 |      0   2018-01-01 12:00:00
 |      1   2018-01-01 12:00:00
 |      2   2018-01-01 12:00:00
 |      dtype: datetime64[ns]
 |
 |      When rounding near a daylight savings time transition, use ``ambiguous`` or
 |      ``nonexistent`` to control how the timestamp should be re-localized.
 |
 |      >>> rng_tz = pd.DatetimeIndex(["2021-10-31 03:30:00"], tz="Europe/Amsterdam")
 |
 |      >>> rng_tz.floor("2h", ambiguous=False)
 |      DatetimeIndex(['2021-10-31 02:00:00+01:00'],
 |                    dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
 |
 |      >>> rng_tz.floor("2h", ambiguous=True)
 |      DatetimeIndex(['2021-10-31 02:00:00+02:00'],
 |                    dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
 |
 |  strftime(self, *args, **kwargs) from pandas.core.accessor.PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>
 |      Convert to Index using specified date_format.
 |
 |      Return an Index of formatted strings specified by date_format, which
 |      supports the same string format as the python standard library. Details
 |      of the string format can be found in `python string format
 |      doc <https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior>`__.
 |
 |      Formats supported by the C `strftime` API but not by the python string format
 |      doc (such as `"%R"`, `"%r"`) are not officially supported and should be
 |      preferably replaced with their supported equivalents (such as `"%H:%M"`,
 |      `"%I:%M:%S %p"`).
 |
 |      Note that `PeriodIndex` support additional directives, detailed in
 |      `Period.strftime`.
 |
 |      Parameters
 |      ----------
 |      date_format : str
 |          Date format string (e.g. "%Y-%m-%d").
 |
 |      Returns
 |      -------
 |      ndarray[object]
 |          NumPy ndarray of formatted strings.
 |
 |      See Also
 |      --------
 |      to_datetime : Convert the given argument to datetime.
 |      DatetimeIndex.normalize : Return DatetimeIndex with times to midnight.
 |      DatetimeIndex.round : Round the DatetimeIndex to the specified freq.

## Processing NAs

### df.dropna() : drop NAs

In [ ]:
#axis = 0 or 'index' vs. 1 or 'columns'
df.dropna(axis = 'columns'), df.dropna(axis = 'columns').shape

(     Wind  Temp  Month  Day
 0     7.4    67      5    1
 1     8.0    72      5    2
 2    12.6    74      5    3
 3    11.5    62      5    4
 4    14.3    56      5    5
 ..    ...   ...    ...  ...
 148   6.9    70      9   26
 149  13.2    77      9   27
 150  14.3    75      9   28
 151   8.0    76      9   29
 152  11.5    68      9   30

 [153 rows x 4 columns],
 (153, 4))

In [ ]:
#subset = [] option to ignore other columns
df.dropna(subset = ['Ozone'], how = 'any'), df.dropna(subset = ['Ozone'], how = 'any').shape

(     Ozone  Solar.R  Wind  Temp  Month  Day
 0     41.0    190.0   7.4    67      5    1
 1     36.0    118.0   8.0    72      5    2
 2     12.0    149.0  12.6    74      5    3
 3     18.0    313.0  11.5    62      5    4
 5     28.0      NaN  14.9    66      5    6
 ..     ...      ...   ...   ...    ...  ...
 147   14.0     20.0  16.6    63      9   25
 148   30.0    193.0   6.9    70      9   26
 150   14.0    191.0  14.3    75      9   28
 151   18.0    131.0   8.0    76      9   29
 152   20.0    223.0  11.5    68      9   30

 [116 rows x 6 columns],
 (116, 6))

### df.fillna() : replace NAs with other values

In [ ]:
df.fillna(df.mean())

        Ozone     Solar.R  Wind  Temp  Month  Day
0    41.00000  190.000000   7.4    67      5    1
1    36.00000  118.000000   8.0    72      5    2
2    12.00000  149.000000  12.6    74      5    3
3    18.00000  313.000000  11.5    62      5    4
4    42.12931  185.931507  14.3    56      5    5
..        ...         ...   ...   ...    ...  ...
148  30.00000  193.000000   6.9    70      9   26
149  42.12931  145.000000  13.2    77      9   27
150  14.00000  191.000000  14.3    75      9   28
151  18.00000  131.000000   8.0    76      9   29
152  20.00000  223.000000  11.5    68      9   30

[153 rows x 6 columns]

In [ ]:
df.fillna(df.mean()).isna().sum()

Ozone      0
Solar.R    0
Wind       0
Temp       0
Month      0
Day        0
dtype: int64

In [ ]:
df.loc[]


#data slice 


df.iloc

SyntaxError: invalid syntax (478066586.py, line 1)

In [ ]:
df.loc[:].idxmax() #idxmax(axis = 0) : 최댓값이 포함된 열/행

In [5]:
#data slicing by index

df.iloc[:int(len(df)*0.7)]

     Ozone  Solar.R  Wind  Temp  Month  Day
0     41.0    190.0   7.4    67      5    1
1     36.0    118.0   8.0    72      5    2
2     12.0    149.0  12.6    74      5    3
3     18.0    313.0  11.5    62      5    4
4      NaN      NaN  14.3    56      5    5
..     ...      ...   ...   ...    ...  ...
102    NaN    137.0  11.5    86      8   11
103   44.0    192.0  11.5    86      8   12
104   28.0    273.0  11.5    82      8   13
105   65.0    157.0   9.7    80      8   14
106    NaN     64.0  11.5    79      8   15

[107 rows x 6 columns]

In [ ]:
from sklearn.metrics import root_mean_squared_error

153

In [ ]:
df.corr(numeric_only=True)

## 날짜